on: 
  push: 
    branches:
      - main
name: ğŸ‰ Deploy Dashboard
jobs:
  prepare:
    name: ğŸš€ Deploy
    runs-on: ubuntu-latest
    needs: prepare
    steps:
    - name: ğŸšš Pegando codigo mais recente...
      uses: actions/checkout@v2